version: '3.7'

services:
  web:
    # Указываем директорию ./app, в которой содержится Dockerfile для сборки образа
    build:
      dockerfile: ./Dockerfile
      context: ./

    # Запускаем встроенный сервер Django
    command: python manage.py runserver 0.0.0.0:8000
    # Пробрасываем 8000 порт контейнера на 8000 порт локалхоста(127.0.0.1:8000)
    ports:
      - 127.0.0.1:8000:8000
    # Файл содержащий переменные окружения для контейнера
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres-data: